version: "3"
services:
  ryanair-automation:
    build:
      context: .
      dockerfile: Dockerfile
  selenium-chrome:
    image: selenium/standalone-chrome:3.141.59-20200525
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm